model_params:
  name: 'VQVAE'
  in_channels: 3
  embedding_dim: 64
  num_embeddings: 512
  img_size: 64
  beta: 0.25

data_params:
  data_path: "/home/guest/workplace/zsl/Datasets/"
  train_batch_size: 64
  val_batch_size:  64
  patch_size: 64
  num_workers: 4


exp_params:
  LR: 0.0001
  weight_decay: 0.0
  # scheduler_gamma: 0.9
  kld_weight: 0.00025
  manual_seed: 1265
# exp_params:
#   LR: 0.001        # 最大学习率
#   scheduler_eta_min: 0.00001  # 最小学习率
#   warmup_epochs: 5  # 可调节的warmup时长（建议5-10）
#   weight_decay: 0.0
#   kld_weight: 0.00025
#   manual_seed: 1265

trainer_params:
  gpus: [0,1]
  max_epochs: 100

logging_params:
  save_dir: "/home/guest/workplace/zsl/vqvae-origin/log_sigmod/"
  name: 'VQVAE'
